### ISSUE TITLE
Add "safest" protection level

### ISSUE THREAD

**Issue by ralexstokes** [adiasg/eth2-slashing-protection-rebuild#3]
Add a mode where the user simply generates a protection file where the validator(s) latest actions are:

```json
   "signed_blocks":[
      {
         "slot":"$CURRENT_SLOT"
      }
   ],
   "signed_attestations":[
      {
         "source_epoch":"$CURRENT_EPOCH",
         "target_epoch":"$CURRENT_EPOCH"
      }
   ]
```

with the rationale that the user should not be able to make any slashable data following this protection record at the expense of some operations that would otherwise be safe (and profitable).

This safety holds as long as the current justified epoch is monotonically increasing (refer README for assumptions).

**Comment by adiasg** [comment]
`"source_epoch":"$(CURRENT_EPOCH - 1)"` will also work for the same safety level, while providing an improvement in validator participation

**Comment by adiasg** [comment]
> This safety holds as long as the current justified epoch is monotonically increasing (refer README for assumptions).

When using `{ "source_epoch":"$CURRENT_EPOCH", "target_epoch":"$CURRENT_EPOCH" }`, the safety is not conditional on what has happened in the chain. Rather, the safety holds as long as the validator has always been using an accurate clock, so that there are no attestations with `attestation.data.target.epoch > $CURRENT_EPOCH`.
